<?php 

namespace marygastro\Modules\Base\Database\Seeders;

use DB;
use Illuminate\Database\Seeder;

//modelo(s)
use  marygastro\Modules\Base\Models\Parroquia;

class ParroquiasSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $parroquias = [
            [1, 'Alto Orinoco'],
            [1, 'Huachamacare Acanaña'],
            [1, 'Marawaka Toky Shamanaña'],
            [1, 'Mavaka Mavaka'],
            [1, 'Sierra Parima Parimabé'],
            [2, 'Ucata Laja Lisa'],
            [2, 'Yapacana Macuruco'],
            [2, 'Caname Guarinuma'],
            [3, 'Fernando Girón Tovar'],
            [3, 'Luis Alberto Gómez'],
            [3, 'Pahueña Limón de Parhueña'],
            [3, 'Platanillal Platanillal'],
            [4, 'Samariapo'],
            [4, 'Sipapo'],
            [4, 'Munduapo'],
            [4, 'Guayapo'],
            [5, 'Alto Ventuari'],
            [5, 'Medio Ventuari'],
            [5, 'Bajo Ventuari'],
            [6, 'Victorino'],
            [6, 'Comunidad'],
            [7, 'Casiquiare'],
            [7, 'Cocuy'],
            [7, 'San Carlos de Río Negro'],
            [7, 'Solano'],
            [8, 'Anaco'],
            [8, 'San Joaquín'],
            [9, 'Cachipo'],
            [9, 'Aragua de Barcelona'],
            [11, 'Lechería'],
            [11, 'El Morro'],
            [12, 'Puerto Píritu'],
            [12, 'San Miguel'],
            [12, 'Sucre'],
            [13, 'Valle de Guanape'],
            [13, 'Santa Bárbara'],
            [14, 'El Chaparro'],
            [14, 'Tomás Alfaro'],
            [14, 'Calatrava'],
            [15, 'Guanta'],
            [15, 'Chorrerón'],
            [16, 'Mamo'],
            [16, 'Soledad'],
            [17, 'Mapire'],
            [17, 'Piar'],
            [17, 'Santa Clara'],
            [17, 'San Diego de Cabrutica'],
            [17, 'Uverito'],
            [17, 'Zuata'],
            [18, 'Puerto La Cruz'],
            [18, 'Pozuelos'],
            [19, 'Onoto'],
            [19, 'San Pablo'],
            [20, 'San Mateo'],
            [20, 'El Carito'],
            [20, 'Santa Inés'],
            [20, 'La Romereña'],
            [21, 'Atapirire'],
            [21, 'Boca del Pao'],
            [21, 'El Pao'],
            [21, 'Pariaguán'],
            [22, 'Cantaura'],
            [22, 'Libertador'],
            [22, 'Santa Rosa'],
            [22, 'Urica'],
            [23, 'Píritu'],
            [23, 'San Francisco'],
            [24, 'San José de Guanipa'],
            [25, 'Boca de Uchire'],
            [25, 'Boca de Chávez'],
            [26, 'Pueblo Nuevo'],
            [26, 'Santa Ana'],
            [27, 'Bergantín'],
            [27, 'Caigua'],
            [27, 'El Carmen'],
            [27, 'El Pilar'],
            [27, 'Naricual'],
            [27, 'San Crsitóbal'],
            [28, 'Edmundo Barrios'],
            [28, 'Miguel Otero Silva'],
            [29, 'Achaguas'],
            [29, 'Apurito'],
            [29, 'El Yagual'],
            [29, 'Guachara'],
            [29, 'Mucuritas'],
            [29, 'Queseras del medio'],
            [30, 'Biruaca'],
            [31, 'Bruzual'],
            [31, 'Mantecal'],
            [31, 'Quintero'],
            [31, 'Rincón Hondo'],
            [31, 'San Vicente'],
            [32, 'Guasdualito'],
            [32, 'Aramendi'],
            [32, 'El Amparo'],
            [32, 'San Camilo'],
            [32, 'Urdaneta'],
            [33, 'San Juan de Payara'],
            [33, 'Codazzi'],
            [33, 'Cunaviche'],
            [34, 'Elorza'],
            [34, 'La Trinidad'],
            [35, 'San Fernando'],
            [35, 'El Recreo'],
            [35, 'Peñalver'],
            [35, 'San Rafael de Atamaica'],
            [36, 'Pedro José Ovalles'],
            [36, 'Joaquín Crespo'],
            [36, 'José Casanova Godoy'],
            [36, 'Madre María de San José'],
            [36, 'Andrés Eloy Blanco'],
            [36, 'Los Tacarigua'],
            [36, 'Las Delicias'],
            [36, 'Choroní'],
            [37, 'Bolívar'],
            [38, 'Camatagua'],
            [38, 'Carmen de Cura'],
            [39, 'Santa Rita'],
            [39, 'Francisco de Miranda'],
            [39, 'Moseñor Feliciano González'],
            [40, 'Santa Cruz'],
            [41, 'José Félix Ribas'],
            [41, 'Castor Nieves Ríos'],
            [41, 'Las Guacamayas'],
            [41, 'Pao de Zárate'],
            [41, 'Zuata'],
            [42, 'José Rafael Revenga'],
            [43, 'Palo Negro'],
            [43, 'San Martín de Porres'],
            [44, 'El Limón'],
            [44, 'Caña de Azúcar'],
            [45, 'Ocumare de la Costa'],
            [46, 'San Casimiro'],
            [46, 'Güiripa'],
            [46, 'Ollas de Caramacate'],
            [46, 'Valle Morín'],
            [47, 'San Sebastían'],
            [48, 'Turmero'],
            [48, 'Arevalo Aponte'],
            [48, 'Chuao'],
            [48, 'Samán de Güere'],
            [48, 'Alfredo Pacheco Miranda'],
            [49, 'Santos Michelena'],
            [49, 'Tiara'],
            [50, 'Cagua'],
            [50, 'Bella Vista'],
            [51, 'Tovar'],
            [52, 'Urdaneta'],
            [52, 'Las Peñitas'],
            [52, 'San Francisco de Cara'],
            [52, 'Taguay'],
            [53, 'Zamora'],
            [53, 'Magdaleno'],
            [53, 'San Francisco de Asís'],
            [53, 'Valles de Tucutunemo'],
            [53, 'Augusto Mijares'],
            [54, 'Sabaneta'],
            [54, 'Juan Antonio Rodríguez Domínguez'],
            [55, 'El Cantón'],
            [55, 'Santa Cruz de Guacas'],
            [55, 'Puerto Vivas'],
            [56, 'Ticoporo'],
            [56, 'Nicolás Pulido'],
            [56, 'Andrés Bello'],
            [57, 'Arismendi'],
            [57, 'Guadarrama'],
            [57, 'La Unión'],
            [57, 'San Antonio'],
            [58, 'Barinas'],
            [58, 'Alberto Arvelo Larriva'],
            [58, 'San Silvestre'],
            [58, 'Santa Inés'],
            [58, 'Santa Lucía'],
            [58, 'Torumos'],
            [58, 'El Carmen'],
            [58, 'Rómulo Betancourt'],
            [58, 'Corazón de Jesús'],
            [58, 'Ramón Ignacio Méndez'],
            [58, 'Alto Barinas'],
            [58, 'Manuel Palacio Fajardo'],
            [58, 'Juan Antonio Rodríguez Domínguez'],
            [58, 'Dominga Ortiz de Páez'],
            [59, 'Barinitas'],
            [59, 'Altamira de Cáceres'],
            [59, 'Calderas'],
            [60, 'Barrancas'],
            [60, 'El Socorro'],
            [60, 'Mazparrito'],
            [61, 'Santa Bárbara'],
            [61, 'Pedro Briceño Méndez'],
            [61, 'Ramón Ignacio Méndez'],
            [61, 'José Ignacio del Pumar'],
            [62, 'Obispos'],
            [62, 'Guasimitos'],
            [62, 'El Real'],
            [62, 'La Luz'],
            [63, 'Ciudad Bolívia'],
            [63, 'José Ignacio Briceño'],
            [63, 'José Félix Ribas'],
            [63, 'Páez'],
            [64, 'Libertad'],
            [64, 'Dolores'],
            [64, 'Santa Rosa'],
            [64, 'Palacio Fajardo'],
            [65, 'Ciudad de Nutrias'],
            [65, 'El Regalo'],
            [65, 'Puerto Nutrias'],
            [65, 'Santa Catalina'],
            [66, 'Cachamay'],
            [66, 'Chirica'],
            [66, 'Dalla Costa'],
            [66, 'Once de Abril'],
            [66, 'Simón Bolívar'],
            [66, 'Unare'],
            [66, 'Universidad'],
            [66, 'Vista al Sol'],
            [66, 'Pozo Verde'],
            [66, 'Yocoima'],
            [66, '5 de Julio'],
            [67, 'Cedeño'],
            [67, 'Altagracia'],
            [67, 'Ascensión Farreras'],
            [67, 'Guaniamo'],
            [67, 'La Urbana'],
            [67, 'Pijiguaos'],
            [68, 'El Callao'],
            [69, 'Gran Sabana'],
            [69, 'Ikabarú'],
            [70, 'Catedral'],
            [70, 'Zea'],
            [70, 'Orinoco'],
            [70, 'José Antonio Páez'],
            [70, 'Marhuanta'],
            [70, 'Agua Salada'],
            [70, 'Vista Hermosa'],
            [70, 'La Sabanita'],
            [70, 'Panapana'],
            [71, 'Andrés Eloy Blanco'],
            [71, 'Pedro Cova'],
            [72, 'Raúl Leoni'],
            [72, 'Barceloneta'],
            [72, 'Santa Bárbara'],
            [72, 'San Francisco'],
            [73, 'Roscio'],
            [73, 'Salóm'],
            [74, 'Tumeremo'],
            [74, 'El Dorado'],
            [74, 'Dalla Costa'],
            [74, 'San Isidro'],
            [75, 'Sucre'],
            [75, 'Aripao'],
            [75, 'Guarataro'],
            [75, 'Las Majadas'],
            [75, 'Moitaco'],
            [76, 'Padre Pedro Chien'],
            [76, 'Río Grande'],
            [77, 'Bejuma'],
            [77, 'Canoabo'],
            [77, 'Simón Bolívar'],
            [78, 'Güigüe'],
            [78, 'Carabobo'],
            [78, 'Tacarigua'],
            [79, 'Mariara'],
            [79, 'Aguas Calientes'],
            [80, 'Ciudad Alianza'],
            [80, 'Guacara'],
            [80, 'Yagua'],
            [81, 'Morón'],
            [81, 'Yagua'],
            [82, 'Tocuyito'],
            [82, 'Independencia'],
            [83, 'Los Guayos'],
            [84, 'Miranda'],
            [85, 'Montalbán'],
            [86, 'Naguanagua'],
            [87, 'Bartolomé Salóm'],
            [87, 'Democracia'],
            [87, 'Fraternidad'],
            [87, 'Goaigoaza'],
            [87, 'Juan José Flores'],
            [87, 'Unión'],
            [87, 'Borburata'],
            [87, 'Patanemo'],
            [88, 'San Diego'],
            [89, 'San Joaquín'],
            [90, 'Candelaria'],
            [90, 'Catedral'],
            [90, 'El Socorro'],
            [90, 'Miguel Peña'],
            [90, 'Rafael Urdaneta'],
            [90, 'San Blas'],
            [90, 'San José'],
            [90, 'Santa Rosa'],
            [90, 'Negro Primero'],
            [91, 'Cojedes'],
            [91, 'Juan de Mata Suárez'],
            [92, 'Tinaquillo'],
            [93, 'El Baúl'],
            [93, 'Sucre'],
            [94, 'La Aguadita'],
            [94, 'Macapo'],
            [95, 'El Pao'],
            [96, 'El Amparo'],
            [96, 'Libertad de Cojedes'],
            [97, 'Rómulo Gallegos'],
            [98, 'San Carlos de Austria'],
            [98, 'Juan Ángel Bravo'],
            [98, 'Manuel Manrique'],
            [99, 'General en Jefe José Laurencio Silva'],
            [100, 'Curiapo'],
            [100, 'Almirante Luis Brión'],
            [100, 'Francisco Aniceto Lugo'],
            [100, 'Manuel Renaud'],
            [100, 'Padre Barral'],
            [100, 'Santos de Abelgas'],
            [101, 'Imataca'],
            [101, 'Cinco de Julio'],
            [101, 'Juan Bautista Arismendi'],
            [101, 'Manuel Piar'],
            [101, 'Rómulo Gallegos'],
            [102, 'Pedernales'],
            [102, 'Luis Beltrán Prieto Figueroa'],
            [103, 'San José (Delta Amacuro)'],
            [103, 'José Vidal Marcano'],
            [103, 'Juan Millán'],
            [103, 'Leonardo Ruíz Pineda'],
            [103, 'Mariscal Antonio José de Sucre'],
            [103, 'Monseñor Argimiro García'],
            [103, 'San Rafael (Delta Amacuro)'],
            [103, 'Virgen del Valle'],
            [10, 'Clarines'],
            [10, 'Guanape'],
            [10, 'Sabana de Uchire'],
            [104, 'Capadare'],
            [104, 'La Pastora'],
            [104, 'Libertador'],
            [104, 'San Juan de los Cayos'],
            [105, 'Aracua'],
            [105, 'La Peña'],
            [105, 'San Luis'],
            [106, 'Bariro'],
            [106, 'Borojó'],
            [106, 'Capatárida'],
            [106, 'Guajiro'],
            [106, 'Seque'],
            [106, 'Zazárida'],
            [106, 'Valle de Eroa'],
            [107, 'Cacique Manaure'],
            [108, 'Norte'],
            [108, 'Carirubana'],
            [108, 'Santa Ana'],
            [108, 'Urbana Punta Cardón'],
            [109, 'La Vela de Coro'],
            [109, 'Acurigua'],
            [109, 'Guaibacoa'],
            [109, 'Las Calderas'],
            [109, 'Macoruca'],
            [110, 'Dabajuro'],
            [111, 'Agua Clara'],
            [111, 'Avaria'],
            [111, 'Pedregal'],
            [111, 'Piedra Grande'],
            [111, 'Purureche'],
            [112, 'Adaure'],
            [112, 'Adícora'],
            [112, 'Baraived'],
            [112, 'Buena Vista'],
            [112, 'Jadacaquiva'],
            [112, 'El Vínculo'],
            [112, 'El Hato'],
            [112, 'Moruy'],
            [112, 'Pueblo Nuevo'],
            [113, 'Agua Larga'],
            [113, 'El Paují'],
            [113, 'Independencia'],
            [113, 'Mapararí'],
            [114, 'Agua Linda'],
            [114, 'Araurima'],
            [114, 'Jacura'],
            [115, 'Tucacas'],
            [115, 'Boca de Aroa'],
            [116, 'Los Taques'],
            [116, 'Judibana'],
            [117, 'Mene de Mauroa'],
            [117, 'San Félix'],
            [117, 'Casigua'],
            [118, 'Guzmán Guillermo'],
            [118, 'Mitare'],
            [118, 'Río Seco'],
            [118, 'Sabaneta'],
            [118, 'San Antonio'],
            [118, 'San Gabriel'],
            [118, 'Santa Ana'],
            [119, 'Boca del Tocuyo'],
            [119, 'Chichiriviche'],
            [119, 'Tocuyo de la Costa'],
            [120, 'Palmasola'],
            [121, 'Cabure'],
            [121, 'Colina'],
            [121, 'Curimagua'],
            [122, 'San José de la Costa'],
            [122, 'Píritu'],
            [123, 'San Francisco'],
            [124, 'Sucre'],
            [124, 'Pecaya'],
            [125, 'Tocópero'],
            [126, 'El Charal'],
            [126, 'Las Vegas del Tuy'],
            [126, 'Santa Cruz de Bucaral'],
            [127, 'Bruzual'],
            [127, 'Urumaco'],
            [128, 'Puerto Cumarebo'],
            [128, 'La Ciénaga'],
            [128, 'La Soledad'],
            [128, 'Pueblo Cumarebo'],
            [128, 'Zazárida'],
            [113, 'Churuguara'],
            [129, 'Camaguán'],
            [129, 'Puerto Miranda'],
            [129, 'Uverito'],
            [130, 'Chaguaramas'],
            [131, 'El Socorro'],
            [132, 'Tucupido'],
            [132, 'San Rafael de Laya'],
            [133, 'Altagracia de Orituco'],
            [133, 'San Rafael de Orituco'],
            [133, 'San Francisco Javier de Lezama'],
            [133, 'Paso Real de Macaira'],
            [133, 'Carlos Soublette'],
            [133, 'San Francisco de Macaira'],
            [133, 'Libertad de Orituco'],
            [134, 'Cantaclaro'],
            [134, 'San Juan de los Morros'],
            [134, 'Parapara'],
            [135, 'El Sombrero'],
            [135, 'Sosa'],
            [136, 'Las Mercedes'],
            [136, 'Cabruta'],
            [136, 'Santa Rita de Manapire'],
            [137, 'Valle de la Pascua'],
            [137, 'Espino'],
            [138, 'San José de Unare'],
            [138, 'Zaraza'],
            [139, 'San José de Tiznados'],
            [139, 'San Francisco de Tiznados'],
            [139, 'San Lorenzo de Tiznados'],
            [139, 'Ortiz'],
            [140, 'Guayabal'],
            [140, 'Cazorla'],
            [141, 'San José de Guaribe'],
            [141, 'Uveral'],
            [142, 'Santa María de Ipire'],
            [142, 'Altamira'],
            [143, 'El Calvario'],
            [143, 'El Rastro'],
            [143, 'Guardatinajas'],
            [143, 'Capital Urbana Calabozo'],
            [144, 'Quebrada Honda de Guache'],
            [144, 'Pío Tamayo'],
            [144, 'Yacambú'],
            [145, 'Fréitez'],
            [145, 'José María Blanco'],
            [146, 'Catedral'],
            [146, 'Concepción'],
            [146, 'El Cují'],
            [146, 'Juan de Villegas'],
            [146, 'Santa Rosa'],
            [146, 'Tamaca'],
            [146, 'Unión'],
            [146, 'Aguedo Felipe Alvarado'],
            [146, 'Buena Vista'],
            [146, 'Juárez'],
            [147, 'Juan Bautista Rodríguez'],
            [147, 'Cuara'],
            [147, 'Diego de Lozada'],
            [147, 'Paraíso de San José'],
            [147, 'San Miguel'],
            [147, 'Tintorero'],
            [147, 'José Bernardo Dorante'],
            [147, 'Coronel Mariano Peraza '],
            [148, 'Bolívar'],
            [148, 'Anzoátegui'],
            [148, 'Guarico'],
            [148, 'Hilario Luna y Luna'],
            [148, 'Humocaro Alto'],
            [148, 'Humocaro Bajo'],
            [148, 'La Candelaria'],
            [148, 'Morán'],
            [149, 'Cabudare'],
            [149, 'José Gregorio Bastidas'],
            [149, 'Agua Viva'],
            [150, 'Sarare'],
            [150, 'Buría'],
            [150, 'Gustavo Vegas León'],
            [151, 'Trinidad Samuel'],
            [151, 'Antonio Díaz'],
            [151, 'Camacaro'],
            [151, 'Castañeda'],
            [151, 'Cecilio Zubillaga'],
            [151, 'Chiquinquirá'],
            [151, 'El Blanco'],
            [151, 'Espinoza de los Monteros'],
            [151, 'Lara'],
            [151, 'Las Mercedes'],
            [151, 'Manuel Morillo'],
            [151, 'Montaña Verde'],
            [151, 'Montes de Oca'],
            [151, 'Torres'],
            [151, 'Heriberto Arroyo'],
            [151, 'Reyes Vargas'],
            [151, 'Altagracia'],
            [152, 'Siquisique'],
            [152, 'Moroturo'],
            [152, 'San Miguel'],
            [152, 'Xaguas'],
            [153, 'Presidente Betancourt'],
            [153, 'Presidente Páez'],
            [153, 'Presidente Rómulo Gallegos'],
            [153, 'Gabriel Picón González'],
            [153, 'Héctor Amable Mora'],
            [153, 'José Nucete Sardi'],
            [153, 'Pulido Méndez'],
            [154, 'La Azulita'],
            [155, 'Santa Cruz de Mora'],
            [155, 'Mesa Bolívar'],
            [155, 'Mesa de Las Palmas'],
            [156, 'Aricagua'],
            [156, 'San Antonio'],
            [157, 'Canagua'],
            [157, 'Capurí'],
            [157, 'Chacantá'],
            [157, 'El Molino'],
            [157, 'Guaimaral'],
            [157, 'Mucutuy'],
            [157, 'Mucuchachí'],
            [158, 'Fernández Peña'],
            [158, 'Matriz'],
            [158, 'Montalbán'],
            [158, 'Acequias'],
            [158, 'Jají'],
            [158, 'La Mesa'],
            [158, 'San José del Sur'],
            [159, 'Tucaní'],
            [159, 'Florencio Ramírez'],
            [160, 'Santo Domingo'],
            [160, 'Las Piedras'],
            [161, 'Guaraque'],
            [161, 'Mesa de Quintero'],
            [161, 'Río Negro'],
            [162, 'Arapuey'],
            [162, 'Palmira'],
            [163, 'San Cristóbal de Torondoy'],
            [163, 'Torondoy'],
            [164, 'Antonio Spinetti Dini'],
            [164, 'Arias'],
            [164, 'Caracciolo Parra Pérez'],
            [164, 'Domingo Peña'],
            [164, 'El Llano'],
            [164, 'Gonzalo Picón Febres'],
            [164, 'Jacinto Plaza'],
            [164, 'Juan Rodríguez Suárez'],
            [164, 'Lasso de la Vega'],
            [164, 'Mariano Picón Salas'],
            [164, 'Milla'],
            [164, 'Osuna Rodríguez'],
            [164, 'Sagrario'],
            [164, 'El Morro'],
            [164, 'Los Nevados'],
            [165, 'Andrés Eloy Blanco'],
            [165, 'La Venta'],
            [165, 'Piñango'],
            [165, 'Timotes'],
            [166, 'Eloy Paredes'],
            [166, 'San Rafael de Alcázar'],
            [166, 'Santa Elena de Arenales'],
            [167, 'Santa María de Caparo'],
            [168, 'Pueblo Llano'],
            [169, 'Cacute'],
            [169, 'La Toma'],
            [169, 'Mucuchíes'],
            [169, 'Mucurubá'],
            [169, 'San Rafael'],
            [170, 'Gerónimo Maldonado'],
            [170, 'Bailadores'],
            [171, 'Tabay'],
            [172, 'Chiguará'],
            [172, 'Estánquez'],
            [172, 'Lagunillas'],
            [172, 'La Trampa'],
            [172, 'Pueblo Nuevo del Sur'],
            [172, 'San Juan'],
            [173, 'El Amparo'],
            [173, 'El Llano'],
            [173, 'San Francisco'],
            [173, 'Tovar'],
            [174, 'Independencia'],
            [174, 'María de la Concepción Palacios Blanco'],
            [174, 'Nueva Bolivia'],
            [174, 'Santa Apolonia'],
            [175, 'Caño El Tigre'],
            [175, 'Zea'],
            [176, 'Aragüita'],
            [176, 'Arévalo González'],
            [176, 'Capaya'],
            [176, 'Caucagua'],
            [176, 'Panaquire'],
            [176, 'Ribas'],
            [176, 'El Café'],
            [176, 'Marizapa'],
            [177, 'Cumbo'],
            [177, 'San José de Barlovento'],
            [178, 'El Cafetal'],
            [178, 'Las Minas'],
            [178, 'Nuestra Señora del Rosario'],
            [179, 'Higuerote'],
            [179, 'Curiepe'],
            [179, 'Tacarigua de Brión'],
            [180, 'Mamporal'],
            [181, 'Carrizal'],
            [182, 'Chacao'],
            [183, 'Charallave'],
            [183, 'Las Brisas'],
            [184, 'El Hatillo'],
            [185, 'Altagracia de la Montaña'],
            [185, 'Cecilio Acosta'],
            [185, 'Los Teques'],
            [185, 'El Jarillo'],
            [185, 'San Pedro'],
            [185, 'Tácata'],
            [185, 'Paracotos'],
            [186, 'Cartanal'],
            [186, 'Santa Teresa del Tuy'],
            [187, 'La Democracia'],
            [187, 'Ocumare del Tuy'],
            [187, 'Santa Bárbara'],
            [188, 'San Antonio de los Altos'],
            [189, 'Río Chico'],
            [189, 'El Guapo'],
            [189, 'Tacarigua de la Laguna'],
            [189, 'Paparo'],
            [189, 'San Fernando del Guapo'],
            [190, 'Santa Lucía del Tuy'],
            [191, 'Cúpira'],
            [191, 'Machurucuto'],
            [192, 'Guarenas'],
            [193, 'San Antonio de Yare'],
            [193, 'San Francisco de Yare'],
            [194, 'Leoncio Martínez'],
            [194, 'Petare'],
            [194, 'Caucagüita'],
            [194, 'Filas de Mariche'],
            [194, 'La Dolorita'],
            [195, 'Cúa'],
            [195, 'Nueva Cúa'],
            [196, 'Guatire'],
            [196, 'Bolívar'],
            [197, 'San Antonio de Maturín'],
            [197, 'San Francisco de Maturín'],
            [198, 'Aguasay'],
            [199, 'Caripito'],
            [200, 'El Guácharo'],
            [200, 'La Guanota'],
            [200, 'Sabana de Piedra'],
            [200, 'San Agustín'],
            [200, 'Teresen'],
            [200, 'Caripe'],
            [201, 'Areo'],
            [201, 'Capital Cedeño'],
            [201, 'San Félix de Cantalicio'],
            [201, 'Viento Fresco'],
            [202, 'El Tejero'],
            [202, 'Punta de Mata'],
            [203, 'Chaguaramas'],
            [203, 'Las Alhuacas'],
            [203, 'Tabasca'],
            [203, 'Temblador'],
            [204, 'Alto de los Godos'],
            [204, 'Boquerón'],
            [204, 'Las Cocuizas'],
            [204, 'La Cruz'],
            [204, 'San Simón'],
            [204, 'El Corozo'],
            [204, 'El Furrial'],
            [204, 'Jusepín'],
            [204, 'La Pica'],
            [204, 'San Vicente'],
            [205, 'Aparicio'],
            [205, 'Aragua de Maturín'],
            [205, 'Chaguamal'],
            [205, 'El Pinto'],
            [205, 'Guanaguana'],
            [205, 'La Toscana'],
            [205, 'Taguaya'],
            [206, 'Cachipo'],
            [206, 'Quiriquire'],
            [207, 'Santa Bárbara'],
            [208, 'Barrancas'],
            [208, 'Los Barrancos de Fajardo'],
            [209, 'Uracoa'],
            [210, 'Antolín del Campo'],
            [211, 'Arismendi'],
            [212, 'García'],
            [212, 'Francisco Fajardo'],
            [213, 'Bolívar'],
            [213, 'Guevara'],
            [213, 'Matasiete'],
            [213, 'Santa Ana'],
            [213, 'Sucre'],
            [214, 'Aguirre'],
            [214, 'Maneiro'],
            [215, 'Adrián'],
            [215, 'Juan Griego'],
            [215, 'Yaguaraparo'],
            [216, 'Porlamar'],
            [217, 'San Francisco de Macanao'],
            [217, 'Boca de Río'],
            [218, 'Tubores'],
            [218, 'Los Baleales'],
            [219, 'Vicente Fuentes'],
            [219, 'Villalba'],
            [220, 'San Juan Bautista'],
            [220, 'Zabala'],
            [222, 'Capital Araure'],
            [222, 'Río Acarigua'],
            [223, 'Capital Esteller'],
            [223, 'Uveral'],
            [224, 'Guanare'],
            [224, 'Córdoba'],
            [224, 'San José de la Montaña'],
            [224, 'San Juan de Guanaguanare'],
            [224, 'Virgen de la Coromoto'],
            [225, 'Guanarito'],
            [225, 'Trinidad de la Capilla'],
            [225, 'Divina Pastora'],
            [226, 'Monseñor José Vicente de Unda'],
            [226, 'Peña Blanca'],
            [227, 'Capital Ospino'],
            [227, 'Aparición'],
            [227, 'La Estación'],
            [228, 'Páez'],
            [228, 'Payara'],
            [228, 'Pimpinela'],
            [228, 'Ramón Peraza'],
            [229, 'Papelón'],
            [229, 'Caño Delgadito'],
            [230, 'San Genaro de Boconoito'],
            [230, 'Antolín Tovar'],
            [231, 'San Rafael de Onoto'],
            [231, 'Santa Fe'],
            [231, 'Thermo Morles'],
            [232, 'Santa Rosalía'],
            [232, 'Florida'],
            [233, 'Sucre'],
            [233, 'Concepción'],
            [233, 'San Rafael de Palo Alzado'],
            [233, 'Uvencio Antonio Velásquez'],
            [233, 'San José de Saguaz'],
            [233, 'Villa Rosa'],
            [234, 'Turén'],
            [234, 'Canelones'],
            [234, 'Santa Cruz'],
            [234, 'San Isidro Labrador'],
            [235, 'Mariño'],
            [235, 'Rómulo Gallegos'],
            [236, 'San José de Aerocuar'],
            [236, 'Tavera Acosta'],
            [237, 'Río Caribe'],
            [237, 'Antonio José de Sucre'],
            [237, 'El Morro de Puerto Santo'],
            [237, 'Puerto Santo'],
            [237, 'San Juan de las Galdonas'],
            [238, 'El Pilar'],
            [238, 'El Rincón'],
            [238, 'General Francisco Antonio Váquez'],
            [238, 'Guaraúnos'],
            [238, 'Tunapuicito'],
            [238, 'Unión'],
            [239, 'Santa Catalina'],
            [239, 'Santa Rosa'],
            [239, 'Santa Teresa'],
            [239, 'Bolívar'],
            [239, 'Maracapana'],
            [241, 'Libertad'],
            [241, 'El Paujil'],
            [241, 'Yaguaraparo'],
            [242, 'Cruz Salmerón Acosta'],
            [242, 'Chacopata'],
            [242, 'Manicuare'],
            [243, 'Tunapuy'],
            [243, 'Campo Elías'],
            [244, 'Irapa'],
            [244, 'Campo Claro'],
            [244, 'Maraval'],
            [244, 'San Antonio de Irapa'],
            [244, 'Soro'],
            [245, 'Mejía'],
            [246, 'Cumanacoa'],
            [246, 'Arenas'],
            [246, 'Aricagua'],
            [246, 'Cogollar'],
            [246, 'San Fernando'],
            [246, 'San Lorenzo'],
            [247, 'Villa Frontado (Muelle de Cariaco)'],
            [247, 'Catuaro'],
            [247, 'Rendón'],
            [247, 'San Cruz'],
            [247, 'Santa María'],
            [248, 'Altagracia'],
            [248, 'Santa Inés'],
            [248, 'Valentín Valiente'],
            [248, 'Ayacucho'],
            [248, 'San Juan'],
            [248, 'Raúl Leoni'],
            [248, 'Gran Mariscal'],
            [249, 'Cristóbal Colón'],
            [249, 'Bideau'],
            [249, 'Punta de Piedras'],
            [249, 'Güiria'],
            [250, 'Andrés Bello'],
            [251, 'Antonio Rómulo Costa'],
            [252, 'Ayacucho'],
            [252, 'Rivas Berti'],
            [252, 'San Pedro del Río'],
            [253, 'Bolívar'],
            [253, 'Palotal'],
            [253, 'General Juan Vicente Gómez'],
            [253, 'Isaías Medina Angarita'],
            [254, 'Cárdenas'],
            [254, 'Amenodoro Ángel Lamus'],
            [254, 'La Florida'],
            [255, 'Córdoba'],
            [256, 'Fernández Feo'],
            [256, 'Alberto Adriani'],
            [256, 'Santo Domingo'],
            [257, 'Francisco de Miranda'],
            [258, 'García de Hevia'],
            [258, 'Boca de Grita'],
            [258, 'José Antonio Páez'],
            [259, 'Guásimos'],
            [260, 'Independencia'],
            [260, 'Juan Germán Roscio'],
            [260, 'Román Cárdenas'],
            [261, 'Jáuregui'],
            [261, 'Emilio Constantino Guerrero'],
            [261, 'Monseñor Miguel Antonio Salas'],
            [262, 'José María Vargas'],
            [263, 'Junín'],
            [263, 'La Petrólea'],
            [263, 'Quinimarí'],
            [263, 'Bramón'],
            [264, 'Libertad'],
            [264, 'Cipriano Castro'],
            [264, 'Manuel Felipe Rugeles'],
            [265, 'Libertador'],
            [265, 'Doradas'],
            [265, 'Emeterio Ochoa'],
            [265, 'San Joaquín de Navay'],
            [266, 'Lobatera'],
            [266, 'Constitución'],
            [267, 'Michelena'],
            [268, 'Panamericano'],
            [268, 'La Palmita'],
            [269, 'Pedro María Ureña'],
            [269, 'Nueva Arcadia'],
            [270, 'Delicias'],
            [270, 'Pecaya'],
            [271, 'Samuel Darío Maldonado'],
            [271, 'Boconó'],
            [271, 'Hernández'],
            [272, 'La Concordia'],
            [272, 'San Juan Bautista'],
            [272, 'Pedro María Morantes'],
            [272, 'San Sebastián'],
            [272, 'Dr. Francisco Romero Lobo'],
            [273, 'Seboruco'],
            [274, 'Simón Rodríguez'],
            [275, 'Sucre'],
            [275, 'Eleazar López Contreras'],
            [275, 'San Pablo'],
            [276, 'Torbes'],
            [277, 'Uribante'],
            [277, 'Cárdenas'],
            [277, 'Juan Pablo Peñalosa'],
            [277, 'Potosí'],
            [278, 'San Judas Tadeo'],
            [279, 'Araguaney'],
            [279, 'El Jaguito'],
            [279, 'La Esperanza'],
            [279, 'Santa Isabel'],
            [280, 'Boconó'],
            [280, 'El Carmen'],
            [280, 'Mosquey'],
            [280, 'Ayacucho'],
            [280, 'Burbusay'],
            [280, 'General Ribas'],
            [280, 'Guaramacal'],
            [280, 'Vega de Guaramacal'],
            [280, 'Monseñor Jáuregui'],
            [280, 'Rafael Rangel'],
            [280, 'San Miguel'],
            [280, 'San José'],
            [281, 'Sabana Grande'],
            [281, 'Cheregüé'],
            [281, 'Granados'],
            [282, 'Arnoldo Gabaldón'],
            [282, 'Bolivia'],
            [282, 'Carrillo'],
            [282, 'Cegarra'],
            [282, 'Chejendé'],
            [282, 'Manuel Salvador Ulloa'],
            [282, 'San José'],
            [283, 'Carache'],
            [283, 'La Concepción'],
            [283, 'Cuicas'],
            [283, 'Panamericana'],
            [283, 'Santa Cruz'],
            [284, 'Escuque'],
            [284, 'La Unión'],
            [284, 'Santa Rita'],
            [284, 'Sabana Libre'],
            [285, 'El Socorro'],
            [285, 'Los Caprichos'],
            [285, 'Antonio José de Sucre'],
            [286, 'Campo Elías'],
            [286, 'Arnoldo Gabaldón'],
            [287, 'Santa Apolonia'],
            [287, 'El Progreso'],
            [287, 'La Ceiba'],
            [287, 'Tres de Febrero'],
            [288, 'El Dividive'],
            [288, 'Agua Santa'],
            [288, 'Agua Caliente'],
            [288, 'El Cenizo'],
            [288, 'Valerita'],
            [289, 'Monte Carmelo'],
            [289, 'Buena Vista'],
            [289, 'Santa María del Horcón'],
            [290, 'Motatán'],
            [290, 'El Baño'],
            [290, 'Jalisco'],
            [291, 'Pampán'],
            [291, 'Flor de Patria'],
            [291, 'La Paz'],
            [291, 'Santa Ana'],
            [292, 'Pampanito'],
            [292, 'La Concepción'],
            [292, 'Pampanito II'],
            [293, 'Betijoque'],
            [293, 'José Gregorio Hernández'],
            [293, 'La Pueblita'],
            [293, 'Los Cedros'],
            [294, 'Carvajal'],
            [294, 'Campo Alegre'],
            [294, 'Antonio Nicolás Briceño'],
            [294, 'José Leonardo Suárez'],
            [295, 'Sabana de Mendoza'],
            [295, 'Junín'],
            [295, 'Valmore Rodríguez'],
            [295, 'El Paraíso'],
            [296, 'Andrés Linares'],
            [296, 'Chiquinquirá'],
            [296, 'Cristóbal Mendoza'],
            [296, 'Cruz Carrillo'],
            [296, 'Matriz'],
            [296, 'Monseñor Carrillo'],
            [296, 'Tres Esquinas'],
            [297, 'Cabimbú'],
            [297, 'Jajó'],
            [297, 'La Mesa de Esnujaque'],
            [297, 'Santiago'],
            [297, 'Tuñame'],
            [297, 'La Quebrada'],
            [298, 'Juan Ignacio Montilla'],
            [298, 'La Beatriz'],
            [298, 'La Puerta'],
            [298, 'Mendoza del Valle de Momboy'],
            [298, 'Mercedes Díaz'],
            [298, 'San Luis'],
            [299, 'Caraballeda'],
            [299, 'Carayaca'],
            [299, 'Carlos Soublette'],
            [299, 'Caruao Chuspa'],
            [299, 'Catia La Mar'],
            [299, 'El Junko'],
            [299, 'La Guaira'],
            [299, 'Macuto'],
            [299, 'Maiquetía'],
            [299, 'Naiguatá'],
            [299, 'Urimare'],
            [300, 'Arístides Bastidas'],
            [301, 'Bolívar'],
            [302, 'Chivacoa'],
            [302, 'Campo Elías'],
            [303, 'Cocorote'],
            [304, 'Independencia'],
            [305, 'José Antonio Páez'],
            [306, 'La Trinidad'],
            [307, 'Manuel Monge'],
            [308, 'Salóm'],
            [308, 'Temerla'],
            [308, 'Nirgua'],
            [309, 'San Andrés'],
            [309, 'Yaritagua'],
            [310, 'San Javier'],
            [310, 'Albarico'],
            [310, 'San Felipe'],
            [311, 'Sucre'],
            [312, 'Urachiche'],
            [313, 'El Guayabo'],
            [313, 'Farriar'],
            [314, 'Isla de Toas'],
            [314, 'Monagas'],
            [315, 'San Timoteo'],
            [315, 'General Urdaneta'],
            [315, 'Libertador'],
            [315, 'Marcelino Briceño'],
            [315, 'Pueblo Nuevo'],
            [315, 'Manuel Guanipa Matos'],
            [316, 'Ambrosio'],
            [316, 'Carmen Herrera'],
            [316, 'La Rosa'],
            [316, 'Germán Ríos Linares'],
            [316, 'San Benito'],
            [316, 'Rómulo Betancourt'],
            [316, 'Jorge Hernández'],
            [316, 'Punta Gorda'],
            [316, 'Arístides Calvani'],
            [317, 'Encontrados'],
            [317, 'Udón Pérez'],
            [318, 'Moralito'],
            [318, 'San Carlos del Zulia'],
            [318, 'Santa Cruz del Zulia'],
            [318, 'Santa Bárbara'],
            [318, 'Urribarrí'],
            [319, 'Carlos Quevedo'],
            [319, 'Francisco Javier Pulgar'],
            [319, 'Simón Rodríguez'],
            [319, 'Guamo-Gavilanes'],
            [321, 'La Concepción'],
            [321, 'San José'],
            [321, 'Mariano Parra León'],
            [321, 'José Ramón Yépez'],
            [322, 'Jesús María Semprún'],
            [322, 'Barí'],
            [323, 'Concepción'],
            [323, 'Andrés Bello'],
            [323, 'Chiquinquirá'],
            [323, 'El Carmelo'],
            [323, 'Potreritos'],
            [324, 'Libertad'],
            [324, 'Alonso de Ojeda'],
            [324, 'Venezuela'],
            [324, 'Eleazar López Contreras'],
            [324, 'Campo Lara'],
            [325, 'Bartolomé de las Casas'],
            [325, 'Libertad'],
            [325, 'Río Negro'],
            [325, 'San José de Perijá'],
            [326, 'San Rafael'],
            [326, 'La Sierrita'],
            [326, 'Las Parcelas'],
            [326, 'Luis de Vicente'],
            [326, 'Monseñor Marcos Sergio Godoy'],
            [326, 'Ricaurte'],
            [326, 'Tamare'],
            [327, 'Antonio Borjas Romero'],
            [327, 'Bolívar'],
            [327, 'Cacique Mara'],
            [327, 'Carracciolo Parra Pérez'],
            [327, 'Cecilio Acosta'],
            [327, 'Cristo de Aranza'],
            [327, 'Coquivacoa'],
            [327, 'Chiquinquirá'],
            [327, 'Francisco Eugenio Bustamante'],
            [327, 'Idelfonzo Vásquez'],
            [327, 'Juana de Ávila'],
            [327, 'Luis Hurtado Higuera'],
            [327, 'Manuel Dagnino'],
            [327, 'Olegario Villalobos'],
            [327, 'Raúl Leoni'],
            [327, 'Santa Lucía'],
            [327, 'Venancio Pulgar'],
            [327, 'San Isidro'],
            [328, 'Altagracia'],
            [328, 'Faría'],
            [328, 'Ana María Campos'],
            [328, 'San Antonio'],
            [328, 'San José'],
            [329, 'Donaldo García'],
            [329, 'El Rosario'],
            [329, 'Sixto Zambrano'],
            [330, 'San Francisco'],
            [330, 'El Bajo'],
            [330, 'Domitila Flores'],
            [330, 'Francisco Ochoa'],
            [330, 'Los Cortijos'],
            [330, 'Marcial Hernández'],
            [331, 'Santa Rita'],
            [331, 'El Mene'],
            [331, 'Pedro Lucas Urribarrí'],
            [331, 'José Cenobio Urribarrí'],
            [332, 'Rafael Maria Baralt'],
            [332, 'Manuel Manrique'],
            [332, 'Rafael Urdaneta'],
            [333, 'Bobures'],
            [333, 'Gibraltar'],
            [333, 'Heras'],
            [333, 'Monseñor Arturo Álvarez'],
            [333, 'Rómulo Gallegos'],
            [333, 'El Batey'],
            [334, 'Rafael Urdaneta'],
            [334, 'La Victoria'],
            [334, 'Raúl Cuenca'],
            [320, 'Sinamaica'],
            [320, 'Alta Guajira'],
            [320, 'Elías Sánchez Rubio'],
            [320, 'Guajira'],
            [335, 'Altagracia'],
            [335, 'Antímano'],
            [335, 'Caricuao'],
            [335, 'Catedral'],
            [335, 'Coche'],
            [335, 'El Junquito'],
            [335, 'El Paraíso'],
            [335, 'El Recreo'],
            [335, 'El Valle'],
            [335, 'La Candelaria'],
            [335, 'La Pastora'],
            [335, 'La Vega'],
            [335, 'Macarao'],
            [335, 'San Agustín'],
            [335, 'San Bernardino'],
            [335, 'San José'],
            [335, 'San Juan'],
            [335, 'San Pedro'],
            [335, 'Santa Rosalía'],
            [335, 'Santa Teresa'],
            [335, 'Sucre (Catia)'],
            [335, '23 de enero']
        ];

        DB::beginTransaction();
        try {
            foreach ($parroquias as $parroquia) {
                Parroquia::create([
                    'municipios_id' => $parroquia[0],
                    'nombre'        => $parroquia[1]
                ]);
            }
        } catch (Exception $e) {
            DB::rollback();
            echo "Error ";
        }
        DB::commit();
    }
}
